language: haskell

matrix:
  allow_failures:
    - env: GHCVER=head

env:
 - GHCVER=head
 - GHCVER=7.6.3
 - GHCVER=7.8.4 QCVER=-2.7.3
 - GHCVER=7.10.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - travis_retry cabal-1.18 update # commenting out shortens testing time
 - travis_retry cabal-1.18 install template-haskell${THVER} QuickCheck${QCVER}

after_success:
 - cat dist/test/hPDB-examples-*-ParserPerformance.log # display timings

install:
 - travis_retry cabal-1.18 install --only-dependencies
 - cabal-1.18 install --enable-tests

script:
 - echo "All done."
